name: Coverage

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '**.cpp', '**.hpp*', '**.cmake', '**/CMakeLists.txt' ]

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build lcov googletest                                                             \
                               gcc-12 g++-12 libstdc++-12-dev lld-14
          sudo ln -sf /usr/bin/lld-14 /usr/local/bin/ld

          sudo update-alternatives                                                                                     \
            --install /usr/bin/gcc        gcc        /usr/bin/gcc-12        200                                        \
            --slave   /usr/bin/g++        g++        /usr/bin/g++-12                                                   \
            --slave   /usr/bin/gcc-ar     gcc-ar     /usr/bin/gcc-ar-12                                                \
            --slave   /usr/bin/gcc-nm     gcc-nm     /usr/bin/gcc-nm-12                                                \
            --slave   /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-12                                            \
            --slave   /usr/bin/gcov       gcov       /usr/bin/gcov-12                                                  \
            --slave   /usr/bin/gcov-tool  gcov-tool  /usr/bin/gcov-tool-12                                             \
            --slave   /usr/bin/gcov-dump  gcov-dump  /usr/bin/gcov-dump-12
          sudo update-alternatives --auto gcc

          sudo update-alternatives                                                                                     \
            --install /usr/bin/cpp        cpp        /usr/bin/cpp-12        200
          sudo update-alternatives --auto cpp

          gcc --version; gcov --version

      - name: Configure CMake
        run: |
          cmake -S . -B build           \
            -G "Ninja"                  \
            -DCMAKE_BUILD_TYPE=Coverage \
            -DUSE_IPO=OFF               \

      - name: Build
        run: |
          ninja -C build

      - name: Test
        run: |
          ./

      - name: Collect with lcov
        run: |
          lcov --rc lcov_branch_coverage=1  \
            --gcov-tool gcov                \
            -d build                        \
            -c                              \
            -o total.info
          lcov --rc lcov_branch_coverage=1  \
            -r total.info "/usr/*"          \
            -r total.info "*/external/*"    \
            -r total.info "*/tests/*"       \
            -o total.info

          lcov --rc lcov_branch_coverage=1 --list ./build/total.info

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/total.info
