name: clang-format
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths:
      - "core/**"
      - "tests/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: calculate diff
        run: |
          mkdir -p build 
          git diff --diff-filter=ACMRT --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- core/ tests/ > build/DIFF
      - name: clang-format
        uses: iresearch-toolkit/clang-format-action@1.0.4
